### ISSUE TITLE
SMACK64TRANSMUTE not working with Linux OpenZFS

### ISSUE THREAD

**Issue by TerraTech** [cschaufler/smack-next#1]
Distro: Gentoo amd64/hardened/17.1
Kernel: 5.4.97  (All SMACK options enabled)
zfs: 0.8.6

I started working with SMACK a couple days ago and I ran across a bug tonight with the transmute ability.

I ran the procedure found here:  https://security.stackexchange.com/questions/141929/linux-kernel-security-module-smack-transmutation-example

This is the log from my test runs:
```
vm-gentoo-smack / # mkdir /tmp/test   <==(this is a zfs filesystem)
vm-gentoo-smack / # cd /tmp/test
vm-gentoo-smack /tmp/test # chsmack -a dir_label .
vm-gentoo-smack /tmp/test # chsmack .
. access="dir_label"

vm-gentoo-smack /tmp/test # echo "process_label dir_label wx" | smackload
vm-gentoo-smack /tmp/test # echo process_label >/proc/self/attr/current
vm-gentoo-smack /tmp/test # cat /proc/self/attr/current
process_label

vm-gentoo-smack /tmp/test # touch file1
vm-gentoo-smack /tmp/test # mkdir dir1
vm-gentoo-smack /tmp/test # chsmack
dir1 access="_"
file1 access="_"
**** As you can see, it is being set to "floor" instead of "process_label"

**** Now I'll test transmute


vm-gentoo-smack /tmp/test # rm file*
vm-gentoo-smack /tmp/test # rmdir dir*

vm-gentoo-smack /tmp/test # chsmack -t .
vm-gentoo-smack /tmp/test # chsmack .
. access="dir_label" transmute="TRUE"

vm-gentoo-smack /tmp/test # echo "process_label dir_label wxt" | smackload
vm-gentoo-smack /tmp/test # touch file2
vm-gentoo-smack /tmp/test # mkdir dir2
vm-gentoo-smack /tmp/test # chsmack
./dir1 access="_"
./dir2 access="_"
./file1 access="_"
./file2 access="_"
**** As you can see, it is still being set to "floor" instead of transmutating

**** Thinking this may be a ZFS issue, I ran the same tests on a new tmpfs filesystem

vm-gentoo-smack /tmp/test # cd /var/tmp
vm-gentoo-smack /var/tmp # mkdir tmpfs
vm-gentoo-smack /var/tmp # mount -ttmpfs tmpfs tmpfs
vm-gentoo-smack /var/tmp # cd tmpfs
vm-gentoo-smack /var/tmp/tmpfs # df -h .
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           4.9G     0  4.9G   0% /var/tmp/tmpfs

vm-gentoo-smack /var/tmp/tmpfs # mkdir test
vm-gentoo-smack /var/tmp/tmpfs # chsmack -a dir_label test
vm-gentoo-smack /var/tmp/tmpfs # chsmack
./test access="dir_label"

vm-gentoo-smack /var/tmp/tmpfs # cd test
vm-gentoo-smack /var/tmp/tmpfs # echo "process_label dir_label wx" | smackload
vm-gentoo-smack /var/tmp/tmpfs/test # touch file1
vm-gentoo-smack /var/tmp/tmpfs/test # mkdir dir1
vm-gentoo-smack /var/tmp/tmpfs/test # chsmack
./dir1 access="process_label"
./file1 access="process_label"
**** Now it is properly inheriting the "process_label"

**** Test transmutation now

vm-gentoo-smack /var/tmp/tmpfs/test # chsmack -t .
vm-gentoo-smack /var/tmp/tmpfs/test # echo "process_label dir_label wxt" | smackload
vm-gentoo-smack /var/tmp/tmpfs/test # touch file2
vm-gentoo-smack /var/tmp/tmpfs/test # mkdir dir2
vm-gentoo-smack /var/tmp/tmpfs/test # chsmack
./dir2 access="dir_label" transmute="TRUE"
./file2 access="process_label"
**** Transmutation is properly working as well

**** This got me thinking about ZFS and the 3 different settings for 'xattr'
**** In the first case above, it is set to: 'xattr=sa'
**** For this test, I created a new zfs filesystem '/tmp2' and set 'xattr=on'

vm-gentoo-smack /var/tmp/tmpfs/test # cd /
vm-gentoo-smack / # zfs create -oxattr=on zpool/ROOT/tmp2
vm-gentoo-smack / # findmnt tmp2
TARGET SOURCE          FSTYPE OPTIONS
/tmp2  zpool/ROOT/tmp2 zfs    rw,noatime,xattr,posixacl

vm-gentoo-smack / # cd tmp2
vm-gentoo-smack /tmp2 # echo "process_label dir_label wx" | smackload
vm-gentoo-smack /tmp2 # mkdir test
vm-gentoo-smack /tmp2 # cd test
vm-gentoo-smack /tmp2/test # chsmack -a dir_label .
vm-gentoo-smack /tmp2/test # chsmack
vm-gentoo-smack /tmp2/test # chsmack .
. access="dir_label"

vm-gentoo-smack /tmp2/test # touch file1
vm-gentoo-smack /tmp2/test # mkdir dir1
vm-gentoo-smack /tmp2/test # chsmack
./dir1 access="_"
./file1 access="_"

vm-gentoo-smack /tmp2/test # chsmack -t .
vm-gentoo-smack /tmp2/test # echo "process_label dir_label wxt" | smackload
vm-gentoo-smack /tmp2/test # chsmack .
. access="dir_label" transmute="TRUE"

vm-gentoo-smack /tmp2/test # touch file2
vm-gentoo-smack /tmp2/test # mkdir dir2
vm-gentoo-smack /tmp2/test # chsmack .
. access="dir_label" transmute="TRUE"

vm-gentoo-smack /tmp2/test # chsmack
./dir1 access="_"
./dir2 access="_"
./file2 access="_"
./file1 access="_"
****  Same behavior as the first test case above
```

I looked through the source code, especially around the 'MAY_TRANSMUTE' tests, but nothing jumped out at me that may point to some sort of ZFS weirdness.

Please let me know if there is something I may have overlooked.  Thank you!

**Comment by cschaufler** [comment]
On 2/23/2021 5:12 AM, TerraTech wrote:
>
> Distro: Gentoo amd64/hardened/17.1
> Kernel: 5.4.97 (All SMACK options enabled)
> zfs: 0.8.6
>
> I started working with SMACK a couple days ago and I ran across a bug tonight with the transmute ability.
>
Thank you for this report. I have not been working with OpenZFS.
I will have a look to see if there's a simple resolution.

**Comment by cschaufler** [comment]
On 2/23/2021 5:12 AM, TerraTech wrote:
>
> Distro: Gentoo amd64/hardened/17.1
> Kernel: 5.4.97 (All SMACK options enabled)
> zfs: 0.8.6
>
> I started working with SMACK a couple days ago and I ran across a bug tonight with the transmute ability.
>
> I ran
>
ZFS is willing to have you set xattrs but isn't going to
set them on object creation it appears. ZFS isn't upstream,
which makes it difficult to debug.

**Comment by TerraTech** [comment]
Ugh, that doesn't sound good for ZFS.

Can you point out the exact place in the (SMACK) code where the `set xattrs on object creation` would happen between SMACK and zfs?  I would assume this interop applies to both file and directory creations.

As an aside, could you point out in either ext4 or tmpfs where they are setting xattrs on object creation?  It might give a provide some insight for them to see what works and what doesn't.

That way I can decisively show them where this procedure is breaking down during the interop.

Thanks!

**Comment by TerraTech** [comment]
Do you think there will be other filesystems that might behave like this in the future?

Thinking about it, perhaps there should be a validation test to see if the xattrs were set on object creation (1-step) and if not perform a 2-step procedure.

psuedo (simplified to just on copying the process label to new object)
```
# echo process_label > /proc/self/attr/current
# mkdir /tmp/test (dir should have security.SMACK64=process_label)
# cd /tmp/test
# touch file1  (file should have security.SMACK64=process_label)
```
In the kernel:
```
create+set_xattrs "file1"  (1-step)
if file1.security.SMACK64 != "subject.current.label":
  setxattr file1.security.SMACK64=process_label   (2-step)
  if ! retest proper labelling:
    pr_warn("could not properly set security.SMACK64 label")
```
For speed, SMACK could have a list of filesystems that require the 2-step procedure and avoid the retest - however would require future grooming of the list (in case ZFS and others have a final disposition of _won't fix_).

**Comment by TerraTech** [comment]
> ZFS is willing to have you set xattrs but isn't going to set them on object creation it appears. ZFS isn't upstream, which makes it difficult to debug.

Do you know if this impacts `selinux` as well?

**Comment by cschaufler** [comment]
On 2/23/2021 4:48 PM, TerraTech wrote:
>
>     ZFS is willing to have you set xattrs but isn't going to set them on object creation it appears. ZFS isn't upstream, which makes it difficult to debug.
>
> Do you know if this impacts |selinux| as well?
>
I can't say for sure, but I expect that it does. SELinux goes
out of its way to relabel filesystems on boot. That may hide the
object creation issue. Smack and SELinux use similar, but not
identical, mechanisms to deal with files that don't have labels.
It is possible that SELinux works correctly, but I haven't looked
to see.

**Comment by cschaufler** [comment]
On 2/23/2021 4:45 PM, TerraTech wrote:
>
> Do you think there will be other filesystems that might behave like this in the future?
>
Over the years we've seen some filesystem behavior that was
quite surprising. BTRFS, for example, was very lazy about initializing
inodes. This led to all sorts of problems. NFS claims to support labeling,
but to my knowledge no one has gotten it to work except for a single
SELinux configuration. OverlayFS is it's own beast. Yes, I would expect
this or similar behavior on other filesystems.

> Thinking about it, perhaps there should be a validation test to see if the xattrs was set on object creation (1-step) and if not perform a 2-step procedure.
>
> psuedo (simplified to just on copying the process label to new object)
>
> |# echo process_label > /proc/self/attr/current # mkdir /tmp/test # cd /tmp/test # touch file1 (it should have security.SMACK64=process_label) |
>
> In the kernel:
>
> |create+set_xattrs "file1" (1-step) if file1.security.SMACK64 != "subject.current.label": setxattr file1.security.SMACK64=process_label (2-step) if ! retest proper labelling: pr_warn("could not properly set security.SMACK64 label") |
>
> For speed, SMACK could have a list of filesystems that require the 2-step procedure and avoid the retest - however would require future grooming of the list.
>
Testing filesystems for correct Smack behavior is a grand idea.
I do not, unfortunately, have anyone volunteering to do it.

**Comment by cschaufler** [comment]
On 2/23/2021 4:30 PM, TerraTech wrote:
>
> Ugh, that doesn't sound good for ZFS.
>
> Can you point out the exact place in the code where the |set xattrs on object creation| would happen between SMACK and zfs? I would assume this interop applies to both file and directory creations.
>
It's going to happen in smack_d_instantiate(). I'm willing to
wager a beverage that ZFS has "optimized" its use of security_d_instantiate()
in such a way that it isn't called in all the places it needs to be.

**Comment by TerraTech** [comment]
Just a quick update.  I instrumented `smack_d_instantiate()` and found where the execution path diverges between `zfs` and `ext4`.

`ext4: TRUE`
`zfs: FALSE`

https://github.com/cschaufler/smack-next/blob/9140d8bdd4c5a04abe181bb300378355d56990a4/security/smack/smack_lsm.c#L3420

rc = -61 [ENODATA - No data available]

All other execution flow is the same, for a simple `$ touch file1` test in both filesystems.

I'm still digging into this to see if it can be fixed properly (in either realm).  Since I'm running into a deadline on a big project that needs SMACK and ZFS, I'm thinking if there are structural changes needed to ZFS, that I may need to whack it with a hammer and hack in a custom callback between both realms

**Comment by TerraTech** [comment]
Resolved via: https://github.com/openzfs/zfs/pull/11839

**Comment by TerraTech** [comment]
Resolved via: https://github.com/openzfs/zfs/pull/11839

**Comment by cschaufler** [comment]
Thank you for following through on resolving this issue.
